# Generated by Django 5.2 on 2025-04-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
            ],
        ),
    ]
